### ISSUE TITLE
Hello, I made an error when running. Can you give me some suggestions

### ISSUE THREAD

**Issue by njnj0314** [craigleili/SRFeat#1]
Hello, I made an error when running. Can you give me some suggestions

/home/y20/anaconda3/envs/SRFeat-main/bin/python /media/y20/MyPassport/nj/SRFeat-main/trainer_srfeats.py skip_train=False config=exp/srfeats_faust_scape.yml
/home/y20/anaconda3/envs/SRFeat-main/lib/python3.6/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 9000). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "/media/y20/MyPassport/nj/SRFeat-main/trainer_srfeats.py", line 308, in <module>
    run_trainer(Trainer)
  File "/media/y20/MyPassport/nj/SRFeat-main/utils/misc.py", line 148, in run_trainer
    trainer.train()
  File "/media/y20/MyPassport/nj/SRFeat-main/trainer_srfeats.py", line 255, in train
    self._init_train()
  File "/media/y20/MyPassport/nj/SRFeat-main/trainer_srfeats.py", line 93, in _init_train
    num_workers=cfg.data.num_workers)
  File "/media/y20/MyPassport/nj/SRFeat-main/data/__init__.py", line 120, in get_data_loader
    DATASETS[dname](mode, data_root, num_eigenbasis, augments) for dname in data_names
  File "/media/y20/MyPassport/nj/SRFeat-main/data/__init__.py", line 120, in <listcomp>
    DATASETS[dname](mode, data_root, num_eigenbasis, augments) for dname in data_names
  File "/media/y20/MyPassport/nj/SRFeat-main/data/__init__.py", line 32, in get_faust_set
    transforms=tsfm)
  File "/media/y20/MyPassport/nj/SRFeat-main/data/faustscape.py", line 68, in __init__
    normals=vertex_normals_th,
  File "/media/y20/MyPassport/nj/SRFeat-main/diffusion_net/geometry.py", line 583, in get_operators
    normals=normals)
  File "/media/y20/MyPassport/nj/SRFeat-main/diffusion_net/geometry.py", line 335, in compute_operators
    L, M = robust_laplacian.point_cloud_laplacian(verts_np)
  File "/home/y20/anaconda3/envs/SRFeat-main/lib/python3.6/site-packages/robust_laplacian/core.py", line 33, in point_cloud_laplacian
    L, M = rlb.buildPointCloudLaplacian(points, mollify_factor, n_neighbors)
RuntimeError: GC_SAFETY_ASSERT FAILURE from /tmp/pip-req-build-3e9g8ei8/deps/geometry-central/src/surface/surface_mesh.cpp:139 - unreferenced vertex 0
Start training
[*] Loading FAUST_r data
Read geometry::TriangleMesh failed: unknown file extension.

**Comment by craigleili** [comment]
Hello,

It's a bit hard to tell what went wrong from the log. Please check if your data is in the correct format and make sure that the python packages are installed correctly.

All the best.
